/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewController;

import ViewController.AdminLoginView;

/**
 *
 * @author sebas
 */
public class RolView extends javax.swing.JFrame {

    /**
     * Creates new form RolView
     */
    public RolView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        imageBanner = new javax.swing.JLabel();
        loginTeacher = new javax.swing.JButton();
        loginStudent = new javax.swing.JButton();
        addAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(166, 166, 166));
        setBounds(new java.awt.Rectangle(0, 0, 1000, 750));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        Background.setBackground(new java.awt.Color(166, 166, 166));
        Background.setPreferredSize(new java.awt.Dimension(1000, 750));
        Background.setLayout(null);

        imageBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner PMV.png"))); // NOI18N
        imageBanner.setPreferredSize(new java.awt.Dimension(800, 500));
        imageBanner.setSize(new java.awt.Dimension(800, 250));
        Background.add(imageBanner);
        imageBanner.setBounds(100, 80, 800, 250);

        loginTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Docente.png"))); // NOI18N
        loginTeacher.setContentAreaFilled(false);
        loginTeacher.setMargin(new java.awt.Insets(0, 0, 0, 0));
        loginTeacher.setMaximumSize(new java.awt.Dimension(255, 255));
        loginTeacher.setMinimumSize(new java.awt.Dimension(255, 255));
        loginTeacher.setPreferredSize(new java.awt.Dimension(255, 255));
        loginTeacher.setSize(new java.awt.Dimension(200, 200));
        loginTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTeacherActionPerformed(evt);
            }
        });
        Background.add(loginTeacher);
        loginTeacher.setBounds(150, 420, 200, 200);

        loginStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Estudiante.png"))); // NOI18N
        loginStudent.setContentAreaFilled(false);
        loginStudent.setMargin(new java.awt.Insets(0, 0, 0, 0));
        loginStudent.setMaximumSize(new java.awt.Dimension(255, 255));
        loginStudent.setMinimumSize(new java.awt.Dimension(255, 255));
        loginStudent.setPreferredSize(new java.awt.Dimension(255, 255));
        loginStudent.setSize(new java.awt.Dimension(200, 200));
        loginStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginStudentActionPerformed(evt);
            }
        });
        Background.add(loginStudent);
        loginStudent.setBounds(400, 420, 200, 200);

        addAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Crear cuenta.png"))); // NOI18N
        addAccount.setContentAreaFilled(false);
        addAccount.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addAccount.setMaximumSize(new java.awt.Dimension(255, 255));
        addAccount.setMinimumSize(new java.awt.Dimension(255, 255));
        addAccount.setPreferredSize(new java.awt.Dimension(255, 255));
        addAccount.setSize(new java.awt.Dimension(200, 200));
        addAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountActionPerformed(evt);
            }
        });
        Background.add(addAccount);
        addAccount.setBounds(650, 420, 200, 200);

        getContentPane().add(Background);
        Background.setBounds(0, 0, 1012, 762);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountActionPerformed
        
        NewProfileView newProfile = new NewProfileView();
        newProfile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addAccountActionPerformed

    private void loginStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginStudentActionPerformed
        
        StudentLoginView studentLogin = new StudentLoginView();
        studentLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginStudentActionPerformed

    private void loginTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTeacherActionPerformed
        
        AdminLoginView adminLogin = new AdminLoginView();
        adminLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginTeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RolView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton addAccount;
    private javax.swing.JLabel imageBanner;
    private javax.swing.JButton loginStudent;
    private javax.swing.JButton loginTeacher;
    // End of variables declaration//GEN-END:variables
}
